ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastRefreshAttemptAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "selectedBudgetId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "selectedAccountId" TEXT;
